server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/bankrest
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  config:
    import: optional:file:.env[.properties]

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/migration/db.changelog-master.yaml

  profiles:
    active: dev

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

application:
  jwt:
    access-token-expiration: 1200000
    refresh-token-expiration: 86400000